---
title       : Avaliação das tese e dissertações do IB-USP
subtitle    : 
author      : Comissão de Pós-Graduação
job         : Instituto de Biociências da Universidade de São Paulo
framework: bootstrap
cdn: false
theme: journal
widgets: [disqus, userecho]
highlighter: prettify
hitheme: twitter-bootstrap
linenums: true
disqus:
  shortname: slidify
mode: selfcontained
github:
  user: CPG-IBUSP
  repo: avaliacao-teses
---

# Fichas de avaliação das teses e dissertações
# Comissão de Pós-Graduação do IBUSP
## Apresentação

A CPG do IBUSP aprovou em sua reunião ordinária de 02/12/2010 uma
avaliação interna da qualidade das teses e dissertações do IB. Esta
avaliação foi iniciada em 2011, por meio de uma [ficha](./files/ficha.pdf) que é preenchida
pelos participantes das bancas de avaliação. A
ideia é beneficiar-se da presença de especialistas de outras
instituições que trazemos para as bancas, colocando-os no papel também
de pareceristas das teses e dissertações. O parecerista não precisa se
identificar. Com isso, teremos um sistema de avaliação anônimo por
pares, como em outras ocasiões da vida acadêmica.

É também importante frisar que o objetivo não é uma avaliação
individual das dissertações e teses, ou dos alunos e seus
orientadores. Ao contrário, o objetivo é uma avaliação agregada, do
conjunto de teses e dissertações. Espera-se, com isso, identificar os
aspectos de nossas teses e dissertações que demandam
aperfeiçoamentos. Assim, o que nos interessa são as tendências
centrais e de variação de todas as teses e dissertações, bem como por
programa de pós-graduação e por nível de titulação. 

## Resultados

#### Slides
- [Dados de todos os programas](./geral/slides_geral.html)
- [Programa de Botânica](./botanica/slides_botanica.html)
- [Programa de Ecologia](./ecologia/slides_ecologia.html)
- [Programa de Fisiologia](./fisiologia/slides_fisiologia.html)
- [Programa de Genética](./genetica/slides_genetica.html)
- [Programa de Zoologia](./zoologia/slides_zoologia.html)

## Downloads

#### Dados
- Planilha em formato [RData](./files/ficha.RData) (para R)
- Planilha em formato [csv](./files/ficha_avaliacao_CPG_IB.csv) (planilhas eletrônicas)
- [Metadados](./files/metadata.html)

#### Arquivos
 - [Ficha de avaliação](./files/ficha.pdf)

#### Códigos
 - [Repositório GitHub](https://github.com/CPG-IBUSP/avaliacao-teses): todos os arquivos acima e códigos 
das análises e apresentações.
