library(slidify)
slidify("../index.Rmd")
slidify("../geral/slides_geral.Rmd")
slidify("../botanica/slides_botanica.Rmd")
slidify("../ecologia/slides_ecologia.Rmd")
slidify("../fisiologia/slides_fisiologia.Rmd")
slidify("../genetica/slides_genetica.Rmd")
slidify("../zoologia/slides_zoologia.Rmd")
##system("cd ../")
setwd("../")
publish(user="CPG-IBUSP", repo="avaliacao-teses")
